### ISSUE TITLE
ATooltips need to be above scrollbar

### ISSUE THREAD

**Issue by androche** [cisco-sbg-ui/magna-react#271]
In shell app, `ATooltips` are behind the scrollbar.  When swapping in Tippy from Ribbon components (as an example of expected behavior), we can see the tippy floats above scrollbar (image below)
![Screenshot 2023-03-09 at 10 38 28 AM](https://user-images.githubusercontent.com/112431822/224074989-f27d6606-a559-4526-bea9-fd07cc1ccab3.png)

**To Reproduce**
Hover over avatar here to recreate:
https://xdr.test.iroh.site/incidents/incident-9c4b9c05-729f-4d0b-b967-fe94bde1ae24/detection#0

**Expected behavior**
`<Tippy>` 
![Screenshot 2023-03-09 at 10 35 06 AM](https://user-images.githubusercontent.com/112431822/224074668-e6f0243e-958e-4995-89e2-6eb03f8cf313.png)

**Comment by rwharrisjr** [comment]
This isn't so much a bug as it is a consequence of how AMount works. The tooltip renders inside the closest AMount wrapper in the DOM. In this case it is causing the incident app container to have horizontal scroll. So the tooltip is not actually underneath the scroll bar, the container now scrolls to fit the content.

This is not practical to fix in the library itself..  It would require adding edge detection (complicated) or re-architecing how everything with a z-index or portal works in this library.

---

@androche A simple fix for the issue is to pass `placement="top-right"` to those specific tooltips.

**Comment by androche** [comment]
Chatted offline so adding notes here -  this positions all tooltips to the left (not sure why its called right) so workaround will be to single out the right corner assigneesBox and position it differently there.
