### ISSUE TITLE
Magnetic compliant spinners 

### ISSUE THREAD

**Issue by mvelkCisco** [cisco-sbg-ui/magna-react#332]
See https://magnetic.cisco.com/0a43ab5cd/p/43b10f-progress-and-loading-indicators/b/016102 for the designs.

Some work done in #305 but the design/colors/shape and sizes don't match magnetic.

**Comment by rwharrisjr** [comment]
I think getting rid of the dot loader is a good idea and redo the page for magnetic only, and we could probably just make any reference to a dot loader return a spinner, and document that's what will happen.

The intent of `ALoader` was to make it easy to position children around the loader for the "tiny" variants in the figma referenced in #305. I think it still solves that case. It might be better named `ATinyLoader` since that functionality is more specific to a subset of loader use cases, and more than just a spinner or progressbar itself in a generic context. Incidents uses a loader to the left of observables in some cases (currently a dot, but should be spinner in the future). Moving the styling in to a "Label" component as you suggested in another bullet point would help with that scenario.

Restyling `ASpinLoader` and renaming it to `ASpinner` would keep consistency with `AProgressbar`. 

`ASpinLoaderLabel` would keep consistency with other composable components, and I assume there would be the same for `AProgressbarLabel`. 


@sabrinamokerji was there a design from UX that needed the `indeterminate` state for `AProgressbar`? As @mvelkCisco
 pointed out that's not a pattern magnetic wants to use, but I'm hesitant to say we drop it entirely without seeing the use case.

**Comment by sabrinamokerji** [comment]
@rwharrisjr Alex was thinking of using the indeterminate loader for the top of the Investigate page while more data is being fetched. Currently it shows pending and complete counts, but it's not determinate because the numbers constantly go up and down. Magnetic released those docs after I created that issue though

**Comment by rwharrisjr** [comment]
I think this is resolved by #343
