### ISSUE TITLE
Drawer not unmounting causing shadow at the right of the screen

### ISSUE THREAD

**Issue by mvelkCisco** [cisco-sbg-ui/magna-react#467]
**Describe the bug**
This becomes especially obvious with multiple closed drawers on the screen.

**To Reproduce**
1. Go to investigate detail in any env.
2. See shadow on the right of the screen.

**Expected behavior**
There should be no visible shadows when drawer is closed. Ideally the drawer element should fully unmount when closed.

**Screenshots**
(redacted investigate detail)
<img width="442" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/51229231/926be5a7-5d6e-46c7-92e1-66dca336c747">
<img width="309" alt="image" src="https://github.com/cisco-sbg-ui/magna-react/assets/51229231/31d47d00-5423-4458-9745-76a6f7c7f200">

**Environment (please complete the following information):**
 - Device: mac
 - OS: macOS
 - Browser Chrome
 - Version latest

**Comment by rwharrisjr** [comment]
It's not uncommon for the root of a drawer to remain in the DOM, since it makes the animation transitions easier to handle. The children unmount at the appropriate time, which is the main performance gain.

I'm adding a line to hide the box-shadow when the drawer is hidden, I think that should resolve this issue.
