### ISSUE TITLE
APagination disabled property

### ISSUE THREAD

**Issue by lukaskral** [cisco-sbg-ui/magna-react#612]
**Is your feature request related to a problem? Please describe.**
In the incident manager we're using `APagination` component. Up until now we were using it in js files and were using `disabled` prop. After switching to typescript we noticed that the `disabled` prop is actually not implemented on the magna react side, it would be nice to have it there.

**Additional context**
Just for context, it actually works in the incident manager, because the `disabled` prop is spread to the wrapping `div` element and we're using some global css rules that disable pointer events on any element with the `disabled` prop.

**Comment by androche** [comment]
@lukaskral Just making sure because I would be taking a guess, but do you mean exposing a disabled prop for the arrow buttons?
![Screenshot 2024-02-08 at 9 33 00 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/48729d40-f204-4ce2-a820-670793453e48)

![Screenshot 2024-02-08 at 9 34 41 AM](https://github.com/cisco-sbg-ui/magna-react/assets/112431822/976b9176-6bc8-4693-8fda-33decf5b40b4)

**Comment by lukaskral** [comment]
@androche yeah, exactly, one property that would disable all the buttons inside the component

**Comment by androche** [comment]
ok all buttons - gotcha!
