### ISSUE TITLE
ATextInput escapes \n

### ISSUE THREAD

**Issue by vdineva** [cisco-sbg-ui/magna-react#823]
1. Type into a ATextInput component the value 123.
2. In the console, use vanilla js to get the value of the field
3. Observe it is returned as it should - 123
![Screenshot 2024-08-05 at 11 13 10](https://github.com/user-attachments/assets/9e25d7d3-b680-417a-abf2-790ad480ae62)

1. Type into a ATextInput component the value 123\n
2. In the console, use vanilla js to get the value of the field
3. Observe it is returned as "123\\\n" 

Expected behavior: the value is returned as "123\n"
![Screenshot 2024-08-05 at 11 13 25](https://github.com/user-attachments/assets/bdc97d6c-ad32-4b5e-a027-28a60d917f34)

related issue in the monorepo: https://cisco-sbg.atlassian.net/browse/XDR-4715

**Comment by rwharrisjr** [comment]
This is not a magna-react specific issue, but a consequence of JavaScript.

Trying the same steps in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text gives the same result - the behavior is part of how input fields and the value works. 

I'd suggest manually cleaning up input data with

```js
(str) => str.replace(/\\n/g, '\n')
```

Note that some platforms use `\r` for a newline, but I'm not sure if that would apply to the values in this scenario.


----
Marking this as won't fix since magna shouldn't be modifying data outside of what is native to JavaScript.
